name: DevSecOps IaC and Container Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1. Terraform Security Audit using Checkov
  checkov-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Checkov Static Code Analysis
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          output_format: cli
          soft_fail: false

  # 2. Container Security Audit using Trivy
  trivy-container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t vulnerable-app:latest ./8-container-security

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-app:latest'
          format: 'table'
          exit-code: '1' # Pipeline fails if any HIGH or CRITICAL vulnerability is found
          severity: 'CRITICAL,HIGH'